version: "3"

services: 
  flaskapp:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
      - PYTHON_VERSION=3.7.0-alpine3.8
    environment: 
      - FLASK_ENV=developement
    ports:
      - 5000:5000
    networks: 
      - mynet
  
  redis:
    image: redis:4.0.11-alpine
    networks: 
      - mynet
    volumes:
      - mydata:/data

networks:
  mynet:

volumes:
  mydata: